version: '3'

services:
  broker:
    build: broker/
    networks:
      megasec:
        ipv4_address: 172.28.1.1
    volumes:
      - ./broker:/usr/src/app
    ports:
      - "1883:1883"
    environment:
      - MQTT_BROKER_IP=172.28.1.1

  toggleswitch:
    build: toggleswitch/
    volumes:
      - ./toggleswitch:/usr/src/app
    networks:
      - megasec
    environment:
      - MQTT_BROKER_IP=172.28.1.1      

networks:
  megasec:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16