version: '3'

services:
  broker:
    build: broker/
    networks:
      megasec:
        ipv4_address: 172.28.1.1
    volumes:
      - ./broker:/usr/src/app
    ports:
      - "1883:1883"
    env_file:
      - development.env

  camera:
    build: camera/
    volumes:
      - ./camera:/usr/src/app
    networks:
      - megasec
    env_file:
      - development.env

  motionsensor:
    build: motionsensor/
    volumes:
      - ./motionsensor:/usr/src/app
    networks:
      - megasec
    env_file:
      - development.env

  toggleswitch:
    build: toggleswitch/
    volumes:
      - ./toggleswitch:/usr/src/app
    networks:
      - megasec
    env_file:
      - development.env

networks:
  megasec:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16